packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  spawn-sync: true
  tesseract.js: true
minimumReleaseAgeExclude:
  - "@tanstack/react-start-rsc@0.1.31"
  - "@tanstack/react-start@1.168.32"
  - "@tanstack/router-plugin@1.168.23"
  - "@tanstack/start-plugin-core@1.171.24"
