/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrashIndexRouteImport } from './routes/dashboard/trash/index'
import { Route as DashboardStarredIndexRouteImport } from './routes/dashboard/starred/index'
import { Route as DashboardGuidesIndexRouteImport } from './routes/dashboard/guides/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthEmailVerificationIndexRouteImport } from './routes/auth/email-verification/index'
import { Route as AuthChangePasswordIndexRouteImport } from './routes/auth/change-password/index'
import { Route as DashboardGuidesGuideIdRouteImport } from './routes/dashboard/guides/$guideId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTrashIndexRoute = DashboardTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStarredIndexRoute = DashboardStarredIndexRouteImport.update({
  id: '/starred/',
  path: '/starred/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuidesIndexRoute = DashboardGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerificationIndexRoute =
  AuthEmailVerificationIndexRouteImport.update({
    id: '/email-verification/',
    path: '/email-verification/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthChangePasswordIndexRoute = AuthChangePasswordIndexRouteImport.update({
  id: '/change-password/',
  path: '/change-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardGuidesGuideIdRoute = DashboardGuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guides/$guideId': typeof DashboardGuidesGuideIdRoute
  '/auth/change-password/': typeof AuthChangePasswordIndexRoute
  '/auth/email-verification/': typeof AuthEmailVerificationIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/dashboard/guides/': typeof DashboardGuidesIndexRoute
  '/dashboard/starred/': typeof DashboardStarredIndexRoute
  '/dashboard/trash/': typeof DashboardTrashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/guides/$guideId': typeof DashboardGuidesGuideIdRoute
  '/auth/change-password': typeof AuthChangePasswordIndexRoute
  '/auth/email-verification': typeof AuthEmailVerificationIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/guides': typeof DashboardGuidesIndexRoute
  '/dashboard/starred': typeof DashboardStarredIndexRoute
  '/dashboard/trash': typeof DashboardTrashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guides/$guideId': typeof DashboardGuidesGuideIdRoute
  '/auth/change-password/': typeof AuthChangePasswordIndexRoute
  '/auth/email-verification/': typeof AuthEmailVerificationIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/dashboard/guides/': typeof DashboardGuidesIndexRoute
  '/dashboard/starred/': typeof DashboardStarredIndexRoute
  '/dashboard/trash/': typeof DashboardTrashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/guides/$guideId'
    | '/auth/change-password/'
    | '/auth/email-verification/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/dashboard/guides/'
    | '/dashboard/starred/'
    | '/dashboard/trash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/guides/$guideId'
    | '/auth/change-password'
    | '/auth/email-verification'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/guides'
    | '/dashboard/starred'
    | '/dashboard/trash'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/guides/$guideId'
    | '/auth/change-password/'
    | '/auth/email-verification/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/dashboard/guides/'
    | '/dashboard/starred/'
    | '/dashboard/trash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/trash/': {
      id: '/dashboard/trash/'
      path: '/trash'
      fullPath: '/dashboard/trash/'
      preLoaderRoute: typeof DashboardTrashIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/starred/': {
      id: '/dashboard/starred/'
      path: '/starred'
      fullPath: '/dashboard/starred/'
      preLoaderRoute: typeof DashboardStarredIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guides/': {
      id: '/dashboard/guides/'
      path: '/guides'
      fullPath: '/dashboard/guides/'
      preLoaderRoute: typeof DashboardGuidesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verification/': {
      id: '/auth/email-verification/'
      path: '/email-verification'
      fullPath: '/auth/email-verification/'
      preLoaderRoute: typeof AuthEmailVerificationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/change-password/': {
      id: '/auth/change-password/'
      path: '/change-password'
      fullPath: '/auth/change-password/'
      preLoaderRoute: typeof AuthChangePasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/guides/$guideId': {
      id: '/dashboard/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/dashboard/guides/$guideId'
      preLoaderRoute: typeof DashboardGuidesGuideIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthChangePasswordIndexRoute: typeof AuthChangePasswordIndexRoute
  AuthEmailVerificationIndexRoute: typeof AuthEmailVerificationIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangePasswordIndexRoute: AuthChangePasswordIndexRoute,
  AuthEmailVerificationIndexRoute: AuthEmailVerificationIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuidesGuideIdRoute: typeof DashboardGuidesGuideIdRoute
  DashboardGuidesIndexRoute: typeof DashboardGuidesIndexRoute
  DashboardStarredIndexRoute: typeof DashboardStarredIndexRoute
  DashboardTrashIndexRoute: typeof DashboardTrashIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuidesGuideIdRoute: DashboardGuidesGuideIdRoute,
  DashboardGuidesIndexRoute: DashboardGuidesIndexRoute,
  DashboardStarredIndexRoute: DashboardStarredIndexRoute,
  DashboardTrashIndexRoute: DashboardTrashIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
