/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/auth/route'
import { Route as createOrganizationIndexRouteImport } from './routes/create-organization/index'
import { Route as dashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authChangePasswordIndexRouteImport } from './routes/auth/change-password/index'
import { Route as authEmailVerificationIndexRouteImport } from './routes/auth/email-verification/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as authSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as authSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as dashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as dashboardGuidesIndexRouteImport } from './routes/dashboard/guides/index'
import { Route as dashboardStarredIndexRouteImport } from './routes/dashboard/starred/index'
import { Route as dashboardTrashIndexRouteImport } from './routes/dashboard/trash/index'
import { Route as dashboardGuidesGuideIdRouteImport } from './routes/dashboard/guides/$guideId'
import { Route as dashboardOrganizationsInvitationIndexRouteImport } from './routes/dashboard/organizations/invitation/index'
import { Route as dashboardOrganizationsOrgIdSettingsRouteRouteImport } from './routes/dashboard/organizations/$orgId/settings/route'
import { Route as dashboardOrganizationsOrgIdSettingsIndexRouteImport } from './routes/dashboard/organizations/$orgId/settings/index'
import { Route as dashboardOrganizationsOrgIdSettingsGeneralIndexRouteImport } from './routes/dashboard/organizations/$orgId/settings/general/index'
import { Route as dashboardOrganizationsOrgIdSettingsMembersIndexRouteImport } from './routes/dashboard/organizations/$orgId/settings/members/index'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const createOrganizationIndexRoute = createOrganizationIndexRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordIndexRoute = authChangePasswordIndexRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authEmailVerificationIndexRoute =
  authEmailVerificationIndexRouteImport.update({
    id: '/email-verification',
    path: '/email-verification',
    getParentRoute: () => authRouteRoute,
  } as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardGuidesIndexRoute = dashboardGuidesIndexRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardStarredIndexRoute = dashboardStarredIndexRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardTrashIndexRoute = dashboardTrashIndexRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardGuidesGuideIdRoute = dashboardGuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardOrganizationsInvitationIndexRoute =
  dashboardOrganizationsInvitationIndexRouteImport.update({
    id: '/organizations/invitation',
    path: '/organizations/invitation',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardOrganizationsOrgIdSettingsRouteRoute =
  dashboardOrganizationsOrgIdSettingsRouteRouteImport.update({
    id: '/organizations/$orgId/settings',
    path: '/organizations/$orgId/settings',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardOrganizationsOrgIdSettingsIndexRoute =
  dashboardOrganizationsOrgIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardOrganizationsOrgIdSettingsRouteRoute,
  } as any)
const dashboardOrganizationsOrgIdSettingsGeneralIndexRoute =
  dashboardOrganizationsOrgIdSettingsGeneralIndexRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => dashboardOrganizationsOrgIdSettingsRouteRoute,
  } as any)
const dashboardOrganizationsOrgIdSettingsMembersIndexRoute =
  dashboardOrganizationsOrgIdSettingsMembersIndexRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => dashboardOrganizationsOrgIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/auth': typeof authRouteRouteWithChildren
  '/dashboard': typeof dashboardRouteRouteWithChildren
  '/create-organization': typeof createOrganizationIndexRoute
  '/dashboard/': typeof dashboardIndexRoute
  '/auth/change-password': typeof authChangePasswordIndexRoute
  '/auth/email-verification': typeof authEmailVerificationIndexRoute
  '/auth/reset-password': typeof authResetPasswordIndexRoute
  '/auth/sign-in': typeof authSignInIndexRoute
  '/auth/sign-up': typeof authSignUpIndexRoute
  '/dashboard/guides': typeof dashboardGuidesIndexRoute
  '/dashboard/starred': typeof dashboardStarredIndexRoute
  '/dashboard/trash': typeof dashboardTrashIndexRoute
  '/dashboard/guides/$guideId': typeof dashboardGuidesGuideIdRoute
  '/dashboard/organizations/invitation': typeof dashboardOrganizationsInvitationIndexRoute
  '/dashboard/organizations/$orgId/settings': typeof dashboardOrganizationsOrgIdSettingsRouteRouteWithChildren
  '/dashboard/organizations/$orgId/settings/': typeof dashboardOrganizationsOrgIdSettingsIndexRoute
  '/dashboard/organizations/$orgId/settings/general': typeof dashboardOrganizationsOrgIdSettingsGeneralIndexRoute
  '/dashboard/organizations/$orgId/settings/members': typeof dashboardOrganizationsOrgIdSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/auth': typeof authRouteRouteWithChildren
  '/create-organization': typeof createOrganizationIndexRoute
  '/dashboard': typeof dashboardIndexRoute
  '/auth/change-password': typeof authChangePasswordIndexRoute
  '/auth/email-verification': typeof authEmailVerificationIndexRoute
  '/auth/reset-password': typeof authResetPasswordIndexRoute
  '/auth/sign-in': typeof authSignInIndexRoute
  '/auth/sign-up': typeof authSignUpIndexRoute
  '/dashboard/guides': typeof dashboardGuidesIndexRoute
  '/dashboard/starred': typeof dashboardStarredIndexRoute
  '/dashboard/trash': typeof dashboardTrashIndexRoute
  '/dashboard/guides/$guideId': typeof dashboardGuidesGuideIdRoute
  '/dashboard/organizations/invitation': typeof dashboardOrganizationsInvitationIndexRoute
  '/dashboard/organizations/$orgId/settings': typeof dashboardOrganizationsOrgIdSettingsIndexRoute
  '/dashboard/organizations/$orgId/settings/general': typeof dashboardOrganizationsOrgIdSettingsGeneralIndexRoute
  '/dashboard/organizations/$orgId/settings/members': typeof dashboardOrganizationsOrgIdSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/auth': typeof authRouteRouteWithChildren
  '/dashboard': typeof dashboardRouteRouteWithChildren
  '/create-organization': typeof createOrganizationIndexRoute
  '/dashboard/': typeof dashboardIndexRoute
  '/auth/change-password': typeof authChangePasswordIndexRoute
  '/auth/email-verification': typeof authEmailVerificationIndexRoute
  '/auth/reset-password': typeof authResetPasswordIndexRoute
  '/auth/sign-in': typeof authSignInIndexRoute
  '/auth/sign-up': typeof authSignUpIndexRoute
  '/dashboard/guides': typeof dashboardGuidesIndexRoute
  '/dashboard/starred': typeof dashboardStarredIndexRoute
  '/dashboard/trash': typeof dashboardTrashIndexRoute
  '/dashboard/guides/$guideId': typeof dashboardGuidesGuideIdRoute
  '/dashboard/organizations/invitation': typeof dashboardOrganizationsInvitationIndexRoute
  '/dashboard/organizations/$orgId/settings': typeof dashboardOrganizationsOrgIdSettingsRouteRouteWithChildren
  '/dashboard/organizations/$orgId/settings/': typeof dashboardOrganizationsOrgIdSettingsIndexRoute
  '/dashboard/organizations/$orgId/settings/general': typeof dashboardOrganizationsOrgIdSettingsGeneralIndexRoute
  '/dashboard/organizations/$orgId/settings/members': typeof dashboardOrganizationsOrgIdSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/create-organization'
    | '/dashboard/'
    | '/auth/change-password'
    | '/auth/email-verification'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/guides'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard/guides/$guideId'
    | '/dashboard/organizations/invitation'
    | '/dashboard/organizations/$orgId/settings'
    | '/dashboard/organizations/$orgId/settings/'
    | '/dashboard/organizations/$orgId/settings/general'
    | '/dashboard/organizations/$orgId/settings/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-organization'
    | '/dashboard'
    | '/auth/change-password'
    | '/auth/email-verification'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/guides'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard/guides/$guideId'
    | '/dashboard/organizations/invitation'
    | '/dashboard/organizations/$orgId/settings'
    | '/dashboard/organizations/$orgId/settings/general'
    | '/dashboard/organizations/$orgId/settings/members'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/create-organization'
    | '/dashboard/'
    | '/auth/change-password'
    | '/auth/email-verification'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/guides'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard/guides/$guideId'
    | '/dashboard/organizations/invitation'
    | '/dashboard/organizations/$orgId/settings'
    | '/dashboard/organizations/$orgId/settings/'
    | '/dashboard/organizations/$orgId/settings/general'
    | '/dashboard/organizations/$orgId/settings/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  createOrganizationIndexRoute: typeof createOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof createOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof authChangePasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof authEmailVerificationIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/guides': {
      id: '/dashboard/guides'
      path: '/guides'
      fullPath: '/dashboard/guides'
      preLoaderRoute: typeof dashboardGuidesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/starred': {
      id: '/dashboard/starred'
      path: '/starred'
      fullPath: '/dashboard/starred'
      preLoaderRoute: typeof dashboardStarredIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof dashboardTrashIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/guides/$guideId': {
      id: '/dashboard/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/dashboard/guides/$guideId'
      preLoaderRoute: typeof dashboardGuidesGuideIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/organizations/invitation': {
      id: '/dashboard/organizations/invitation'
      path: '/organizations/invitation'
      fullPath: '/dashboard/organizations/invitation'
      preLoaderRoute: typeof dashboardOrganizationsInvitationIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/organizations/$orgId/settings': {
      id: '/dashboard/organizations/$orgId/settings'
      path: '/organizations/$orgId/settings'
      fullPath: '/dashboard/organizations/$orgId/settings'
      preLoaderRoute: typeof dashboardOrganizationsOrgIdSettingsRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/dashboard/organizations/$orgId/settings/': {
      id: '/dashboard/organizations/$orgId/settings/'
      path: '/'
      fullPath: '/dashboard/organizations/$orgId/settings/'
      preLoaderRoute: typeof dashboardOrganizationsOrgIdSettingsIndexRouteImport
      parentRoute: typeof dashboardOrganizationsOrgIdSettingsRouteRoute
    }
    '/dashboard/organizations/$orgId/settings/general': {
      id: '/dashboard/organizations/$orgId/settings/general'
      path: '/general'
      fullPath: '/dashboard/organizations/$orgId/settings/general'
      preLoaderRoute: typeof dashboardOrganizationsOrgIdSettingsGeneralIndexRouteImport
      parentRoute: typeof dashboardOrganizationsOrgIdSettingsRouteRoute
    }
    '/dashboard/organizations/$orgId/settings/members': {
      id: '/dashboard/organizations/$orgId/settings/members'
      path: '/members'
      fullPath: '/dashboard/organizations/$orgId/settings/members'
      preLoaderRoute: typeof dashboardOrganizationsOrgIdSettingsMembersIndexRouteImport
      parentRoute: typeof dashboardOrganizationsOrgIdSettingsRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authChangePasswordIndexRoute: typeof authChangePasswordIndexRoute
  authEmailVerificationIndexRoute: typeof authEmailVerificationIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authChangePasswordIndexRoute: authChangePasswordIndexRoute,
  authEmailVerificationIndexRoute: authEmailVerificationIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardOrganizationsOrgIdSettingsRouteRouteChildren {
  dashboardOrganizationsOrgIdSettingsIndexRoute: typeof dashboardOrganizationsOrgIdSettingsIndexRoute
  dashboardOrganizationsOrgIdSettingsGeneralIndexRoute: typeof dashboardOrganizationsOrgIdSettingsGeneralIndexRoute
  dashboardOrganizationsOrgIdSettingsMembersIndexRoute: typeof dashboardOrganizationsOrgIdSettingsMembersIndexRoute
}

const dashboardOrganizationsOrgIdSettingsRouteRouteChildren: dashboardOrganizationsOrgIdSettingsRouteRouteChildren =
  {
    dashboardOrganizationsOrgIdSettingsIndexRoute:
      dashboardOrganizationsOrgIdSettingsIndexRoute,
    dashboardOrganizationsOrgIdSettingsGeneralIndexRoute:
      dashboardOrganizationsOrgIdSettingsGeneralIndexRoute,
    dashboardOrganizationsOrgIdSettingsMembersIndexRoute:
      dashboardOrganizationsOrgIdSettingsMembersIndexRoute,
  }

const dashboardOrganizationsOrgIdSettingsRouteRouteWithChildren =
  dashboardOrganizationsOrgIdSettingsRouteRoute._addFileChildren(
    dashboardOrganizationsOrgIdSettingsRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardGuidesIndexRoute: typeof dashboardGuidesIndexRoute
  dashboardStarredIndexRoute: typeof dashboardStarredIndexRoute
  dashboardTrashIndexRoute: typeof dashboardTrashIndexRoute
  dashboardGuidesGuideIdRoute: typeof dashboardGuidesGuideIdRoute
  dashboardOrganizationsInvitationIndexRoute: typeof dashboardOrganizationsInvitationIndexRoute
  dashboardOrganizationsOrgIdSettingsRouteRoute: typeof dashboardOrganizationsOrgIdSettingsRouteRouteWithChildren
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardGuidesIndexRoute: dashboardGuidesIndexRoute,
  dashboardStarredIndexRoute: dashboardStarredIndexRoute,
  dashboardTrashIndexRoute: dashboardTrashIndexRoute,
  dashboardGuidesGuideIdRoute: dashboardGuidesGuideIdRoute,
  dashboardOrganizationsInvitationIndexRoute:
    dashboardOrganizationsInvitationIndexRoute,
  dashboardOrganizationsOrgIdSettingsRouteRoute:
    dashboardOrganizationsOrgIdSettingsRouteRouteWithChildren,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  createOrganizationIndexRoute: createOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
