# syntax=docker/dockerfile:1

FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o ./bin/cliqrelay-api ./cmd/core/main.go

FROM alpine:3.24

WORKDIR /app

COPY --from=builder /build/bin/cliqrelay-api /app/cliqrelay-api

RUN adduser -D -H appuser && \
    chown -R appuser:appuser /app

USER appuser

EXPOSE 8080

ENTRYPOINT ["/app/cliqrelay-api"]
